# Generated by Django 4.2.30 on 2026-06-07 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datasets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField(verbose_name='自然语言问题')),
                ('generated_sql', models.TextField(verbose_name='生成的SQL')),
                ('is_success', models.BooleanField(default=False, verbose_name='是否成功')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('execution_time_ms', models.IntegerField(null=True, verbose_name='执行时间(ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='datasets.dataset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '查询历史',
                'verbose_name_plural': '查询历史',
                'db_table': 'query_history',
            },
        ),
        migrations.AddIndex(
            model_name='queryhistory',
            index=models.Index(fields=['dataset', 'created_at'], name='idx_query_dataset_created'),
        ),
    ]
